config/routes.rb
Rails.application.routes.draw do
    
    resources :students
    
root 'students#index'

get 'students/displayBMI'

end

app/models/student.rb
class Student < ActiveRecord::Base
    validates :Name, presence: true, allow_nil: false,  format: { with: /\A[a-zA-Z]+\z/, message: "field only allows letters" }
    validates :Weight, presence: true, allow_nil: false, numericality: {greater_than: 15, less_than: 600, message: "value must be reasonable for a person"  }
    validates :Height, presence: true, allow_nil: false,  numericality: {greater_than: 30, less_than: 300, message: "value must be reasonable for a person"  }
    validates :GPA, presence: true, allow_nil: false, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 4.33, message: "for SFU is between 0 and 4.33"  }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def displayBMI
  end

  def index
    @students = Student.all
  end

  def show
  end


  def new
    @student = Student.new
  end


  def edit
  end


  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student has been removed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_student
      @student = Student.find(params[:id])
    end

    
    def student_params
      params.require(:student).permit(:Name, :Gender, :Weight, :Height, :Colour, :GPA, :Location, :Faculty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<!DOCTYPE html>
<html>
<body id="formstudent">
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :Gender %>
    <%= f.select :Gender, [['Female','Female'],['Male','Male'],['Other','Other']] %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :'Weight (lbs)' %>
    <%= f.text_field :Weight %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :'Height (cm)' %>
    <%= f.text_field :Height %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :Colour %>
    <%= f.select :Colour, [['Silver','Silver'],['Gray','Gray'],['Red','Red'],['Maroon','Maroon'],['Orange','Orange'],['Olive','Olive'],['Lime','Lime'],['Green','Green'],['Teal','Teal'],['Blue','Blue'],['Navy','Navy'],['Purple','Purple']] %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :GPA %>
    <%= f.text_field :GPA %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :'Campus' %>
    <%= f.select :Location, [['Burnaby','Burnaby'],['Surrey','Surrey'],['Vancouver','Vancouver']] %>
  </div>
  
  <br>
  
  <div class="field">
    <%= f.label :Faculty %>
    <%= f.select :Faculty, [['Arts and Social Sciences','Arts and Social Sciences'],['Business','Business'],['Communication, Art and Technology','Communication, Art and Technology'],['Education','Education'],['Environment','Environment'],['Health Sciences','Health Sciences'],['Science','Science'],['Applied Sciences','Applied Sciences']] %>
  </div>
  
  <br>
  
  <div class="actions">
    <%#  <%= f.submit 'Update Student'%>
    <%= f.submit 'Update Student', id:  'submit_class_1' %>
  </div>
  
  <br>
<% end %>
</body>
</html>

app/views/students/edit.html.erb
<!DOCTYPE html>
<html>
<body id="editstudent">
<h1 id="h1edit">Editing Student</h1>

<%= render 'form' %>

<%# <%= link_to 'Show', @student %> 
<%= link_to 'Cancel', students_path %>
</body>
</html>

app/views/students/new.html.erb
<!DOCTYPE html>
<html>
<body id="newstudent">
<h1 id="h1new">New Student</h1>

<%= render 'form' %>

<%= link_to 'Cancel', students_path %>

</body>
</html>

app/views/students/show.html.erb
<!DOCTYPE html>
<html>
<body id="showstudent">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.Name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.Gender %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @student.Weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @student.Height %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @student.Colour %>
</p>

<p>
  <strong>GPA:</strong>
  <%= @student.GPA %>
</p>

<p>
  <strong>Campus:</strong>
  <%= @student.Location %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.Faculty %>
</p>

<%# <%= link_to 'Edit', edit_student_path(@student) %> 
<%= link_to "<button>Home</button>".html_safe, students_path, :id=>"go-home-btn", :class=>"inbox-sf-add-btn tip" %>
<%# <%= link_to 'Home', students_path %>
</body>
</html>